

services:
  backend:
    build:
      context: ./
      dockerfile: API/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    depends_on:
      - backend

  frontend:
    build:
      context: ./FrontPatient/front-patient
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - gateway
