FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
EXPOSE 5002

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Gateway.csproj", "./"]
RUN dotnet restore "./Gateway.csproj"
COPY . .
RUN dotnet build "Gateway.csproj" -c Release -o /app/build
RUN dotnet publish "Gateway.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
RUN apt-get update && apt-get install -y curl


ENTRYPOINT ["dotnet", "Gateway.dll"]
